apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    description: ee
  name: h$i
  generation: 1
  labels:
    k8s-app: h$i
    qcloud-app: h$i
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: h$i
      qcloud-app: h$i
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: h$i
        qcloud-app: h$i
    spec:
      containers:
        - env:
            - name: PATH
              value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
            - name: hipporegister
              value: $2
          image: hippocoin.tencentcloudcr.com/hippo/coin
          imagePullPolicy: Always
          name: h$1
          resources:
            limits:
              cpu: "3"
              memory: 1Gi
            requests:
              cpu: "2"
              memory: 256Mi
          securityContext:
            privileged: false
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: qcloudregistrykey
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30