apiVersion: v1
kind: Service
metadata:
  name: {}
  namespace: default
spec:
  ports:
    - name: 8080-8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: 9000-9000-tcp
      port: 9000
      protocol: TCP
      targetPort: 9000
  selector:
    k8s-app: {}
    qcloud-app: {}
  type: LoadBalancer